### ISSUE TITLE
[BUG] Config on A+ is bugged

### ISSUE THREAD

**Issue by Flobbah** [JustLazzy/jl-carboost#26]
## Before you describe your issue.

* Are you using the latest QB-Core 
* [Yes]
* Did you follow all steps in the readme 
* [Yes]
* Have you got all dependencies installed 
* [Yes]
* Have you renamed any of the files/folders 
* [Yes]
* What version of jl-carboost are you running? 
* [Latest]

* ISSUE *
In config.lua there is a bug within the A+ spawning.
It looks like this:
`['A+'] = {
        location = {
            vector4(215.76, 758.29, 204.66, 42.63)
        },
        car = {
            'jester2',
        },
        priceminimum = 30,
        pricemaximum = 41,
        spawnnpc = true,
        attempt = 2,
        vinprice = 32
    },`
    but it should look like this:
`['A+'] = {
        location = {
            [1] = {
                car = vector4(215.31, 758.66, 204.65, 38.15),
                npc = {
                    vector3(228.68, 765.78, 204.98),
                    vector3(199.77, 776.69, 205.97),
                    vector3(214.39, 784.04, 204.34)
                },
            }
        },
        car = {
            'jester2',
        },
        priceminimum = 30,
        pricemaximum = 41,
        spawnnpc = true,
        attempt = 2,
        vinprice = 32
    },`

**Comment by Flobbah** [comment]
Sorry, don't know how to pr :(

https://github.com/Flobbah/jl-carboost/commit/8e062623753db91419011b649dc47cc0757ce806

**Comment by Kentainfr** [comment]
Hi, thank you for your bug report. JustLazzy will take care of this issue when he is available.

**Comment by JustLazzy** [comment]
Thank you for your bug report, I already made a change to it, 👋🏻
