### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by SmalltownRP** [JustLazzy/jl-carboost#28]
## Before you describe your issue.

* Are you using the latest QB-Core - yes
* Did you follow all steps in the readme-yes
* Have you got all dependencies installed-yes
* Have you renamed any of the files/folders-yes
* What version of jl-carboost are you running?-latest

* ISSUE *
YOUR ISSUE HERE
Hi getting error jl-boost-main/html/index.html when starting the script any idea what messed up ? 
![image](https://user-images.githubusercontent.com/66795038/161167515-947b1110-b1cd-4342-88ea-80eaa9fe7611.png)

**Comment by JustLazzy** [comment]
Make sure the folder name is jl-carboost not jl-carboost-main

**Comment by SmalltownRP** [comment]
how the hell did i miss that sorry for wasting your time bro big respect for replying
