### ISSUE TITLE
SCRIPT ERROR attempt to index a nil value (global 'Lang')

### ISSUE THREAD

**Issue by lessknight09** [JustLazzy/jl-carboost#7]
my error
[  script:jl-carboost] SCRIPT ERROR: @jl-carboost/server/main.lua:281: attempt to index a nil value (global 'Lang')
[  script:jl-carboost] > ref (@jl-carboost/server/main.lua:281)
[  script:jl-carboost] > rawQuery (@oxmysql/dist/build.js:21700)
[  script:jl-carboost] > processTicksAndRejections (node:internal/process/task_queues:96)
[      script:oxmysql] SCRIPT ERROR in promise (unhandled): Error: jl-carboost was unable to execute a query!
[      script:oxmysql] Error in nested ref call.
[      script:oxmysql] INSERT INTO boost_contract (owner, data, started, expire) VALUES (?, ?, NOW(),DATE_ADD(NOW(), INTERVAL ? HOUR)) ["AOF71603","{\"plate\":\"QP3083\",\"tier\":\"D\",\"owner\":\"Herbert\",\"car\":\"rebla\"}",5]
[      script:oxmysql] > rawQuery (@oxmysql/dist/build.js:21702)
[      script:oxmysql] > processTicksAndRejections (node:internal/process/task_queues:96)
[      script:oxmysql]

**Comment by Kentainfr** [comment]
Hi ! Thank you for reporting your bug. Sadly we only take bug report on discord. You can find the link here : https://discord.gg/fqUjRyhW2z 

Have a good one.

**Comment by JustLazzy** [comment]
You have locale system on your qb core?
